### ISSUE TITLE
Bug Filtering DataCollection by Query

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#390]
**Describe the bug**
When you filter a DataCollection by a Query the filter fails.

**To Reproduce**
1. Go to https://design.digiserve.org/home
2. Click on `AB Designer`->`Activity Photos PWA`->`Data Collections`->`PWA Teams`
3. The error below is what the server reports.

```
System notification received, but Sentry not set up" {"domain":"developer","error":{"_context":"[{\"location\":\"ABModelConvertQueryConditions\",\"sql\":\"-- unknown --\",\"error\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlMessage\":\"Unknown column 'null.uuid' in 'field list'\",\"sqlState\":\"42S22\",\"index\":0,\"sql\":\"select `null.uuid` from `AB_ActivityPhotosPWA_View_MyAssignments` where ( `c0909922.Owner User` = 'James' )\",\"name\":\"Error\",\"message\":\"select `null.uuid` from `AB_ActivityPhotosPWA_View_MyAssignments` where ( `c0909922.Owner User` = 'James' ) - ER_BAD_FIELD_ERROR: Unknown column 'null.uuid' in 'field list'\",\"stack\":\"Error: ER_BAD_FIELD_ERROR: Unknown column 'null.uuid' in 'field list'\\n    at Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\\n    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)\\n    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)\\n    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)\\n    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)\\n    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)\\n    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)\\n    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)\\n    at Socket.emit (node:events:513:28)\\n    at addChunk (node:internal/streams/readable:324:12)\\n    at readableAddChunk (node:internal/streams/readable:297:9)\\n    at Readable.push (node:internal/streams/readable:234:10)\\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\\n    --------------------\\n    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)\\n    at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)\\n    at /app/AppBuilder/node_modules/knex/lib/dialects/mysql/index.js:134:18\\n    at new Promise (<anonymous>)\\n    at Client_MySQL._query (/app/AppBuilder/node_modules/knex/lib/dialects/mysql/index.js:128:12)\\n    at Client_MySQL.query (/app/AppBuilder/node_modules/knex/lib/client.js:168:17)\\n    at Runner.query (/app/AppBuilder/node_modules/knex/lib/runner.js:151:36)\\n    at /app/AppBuilder/node_modules/knex/lib/runner.js:40:23\\n    at /app/AppBuilder/node_modules/knex/lib/runner.js:277:24\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"}}]","name":"Error","message":"Error running query:","stack":"Error: Error running query:\n    at ABFactory.toError (/app/AppBuilder/ABFactory.js:483:19)\n    at /app/AppBuilder/policies/ABModelConvertQueryConditions.js:128:25\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"info":{"context":"Service:appbuilder.model-get: ERROR reducing conditions:","cond":{"where":{"glue":"and","rules":[{"key":"457556e2-9029-4bb3-be17-98eb314bf89a","rule":"in_query","value":"6fc7036f-823c-4d03-9c2f-0b448ed72e96"}]},"sort":[],"populate":true,"limit":20},"tenantID":"db80e601-2da2-4026-b32e-36580f3c9318","jobID":"JLpF2G9Bk","requestID":"PXhiI6Qcga","serviceKey":"appbuilder","user":{"uuid":"187500e9-25fb-45a3-b74e-256ee57bda36","username":"James","email":"james@digiserve.org","languageCode":"en"}},"callStack":"Error: just getting my stack\n    at ABNotification.notify (/app/node_modules/@digiserve/ab-utils/utils/reqNotification.js:25:22)\n    at ABRequestService.notify (/app/node_modules/@digiserve/ab-utils/utils/reqService.js:562:27)\n    at ABRequestService.notify.developer (/app/node_modules/@digiserve/ab-utils/utils/reqService.js:178:15)\n    at /app/handlers/model-get.js:186:36\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**
The query is not building the SQL statement properly and instead of 

`select "null.uuid" from "AB_ActivityPhotosPWA_View_MyAssignments"` 

it should be 

`select "BASE_OBJECT.uuid" from "AB_ActivityPhotosPWA_View_MyAssignments"`

**Server**
Design DigiServe (but probably on all servers)

**Comment by jamesduncan** [comment]
Not sure...but I added more data to the Query and it is working now...very strange.
